# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'


User.destroy_all
Writer.destroy_all
Book.destroy_all
Bookshelf.destroy_all
Review.destroy_all
Tag.destroy_all
Tagging.destroy_all

# u1 = User.create(username: "song1", email:"song1", password:111111)
# u2 = User.create(username: "song2", email:"song2", password:111111)

# w1 = Writer.create(name:"sailormoon", born:"moon", description:"in the name of the moon, I'll punish you")
# w2 = Writer.create(name:"sailormercury", born:"mercury", description:"same")
# w3 = Writer.create(name:"sailorvenus", born:"venus", description:"same")
# w4 = Writer.create(name:"sailormars", born:"mars", description:"same")

# b[1] = Book.create(title:"demobook", writer_id: w1.id, description:"incredible demo book", publish_at: "01/01/2020", language: "English", isbn: 123456789)
# b[2] = Book.create(title:"yourbook", writer_id: w2.id, description:"must be a good book", publish_at: "02/01/2020", language: "English", isbn: 123456689)
# b[3] = Book.create(title:"yourbook2", writer_id: w1.id, description:"must be a good book", publish_at: "02/01/2010", language: "English", isbn: 23456689)
# b[4] = Book.create(title:"yourbook3", writer_id: w3.id, description:"must be a good book", publish_at: "02/01/2015", language: "English", isbn: 1234566899)
# b[5] = Book.create(title:"yourbook4", writer_id: w4.id, description:"must be a good book", publish_at: "02/01/2016", language: "English", isbn: 12324233456689)


# s1 =Bookshelf.create(user_id: u1.id, book_id:b[1].id, title: "Read")
# s2 =Bookshelf.create(user_id: u1.id, book_id:b[2].id, title: "Reading")
# s3 =Bookshelf.create(user_id: u1.id, book_id:b[3].id, title: "Read")
# s4 =Bookshelf.create(user_id: u1.id, book_id:b[4].id, title: "Want to Read")

# r1 = Review.create(user_id: u1.id, book_id:b[1].id, rate: 4, body:"very good!")
# r2 = Review.create(user_id: u1.id, book_id:b[2].id, rate: 5, body:"good!")
# r3 = Review.create(user_id: u1.id, book_id:b[3].id, rate: 2)
# r4 = Review.create(user_id: u1.id, book_id:b[4].id, rate: 3)
# r5 = Review.create(user_id: u2.id, book_id:b[1].id, rate: 5)


# t1 = Tag.create(name:"demo")
# t2 = Tag.create(name:"fiction")
# t3 = Tag.create(name:"philosophy")
# tg1 = Tagging.create(user_id:u1.id, book_id:b[1].id, tag_id:t1.id)
# tg2 = Tagging.create(user_id:u1.id, book_id:b[2].id, tag_id:t2.id)
# tg3 = Tagging.create(user_id:u1.id, book_id:b[3].id, tag_id:t2.id)
# tg4 = Tagging.create(user_id:u1.id, book_id:b[1].id, tag_id:t3.id)
# tg5 = Tagging.create(user_id:u2.id, book_id:b[1].id, tag_id:t1.id)



u0 = User.create(username:'song0', email:'song0', password:111111)
u1 = User.create(username:'song1', email:'song1', password:111111)
u2 = User.create(username:'song2', email:'song2', password:111111)
u3 = User.create(username:'song3', email:'song3', password:111111)
u4 = User.create(username:'song4', email:'song4', password:111111)
u5 = User.create(username:'song5', email:'song5', password:111111)
u6 = User.create(username:'song6', email:'song6', password:111111)
u7 = User.create(username:'song7', email:'song7', password:111111)
u8 = User.create(username:'song8', email:'song8', password:111111)
u9 = User.create(username:'song9', email:'song9', password:111111)
u10 = User.create(username:'song10', email:'song10', password:111111)
u11 = User.create(username:'song11', email:'song11', password:111111)
u12 = User.create(username:'song12', email:'song12', password:111111)
u13 = User.create(username:'song13', email:'song13', password:111111)
u14 = User.create(username:'song14', email:'song14', password:111111)
u15 = User.create(username:'song15', email:'song15', password:111111)
u16 = User.create(username:'song16', email:'song16', password:111111)
u17 = User.create(username:'song17', email:'song17', password:111111)
u18 = User.create(username:'song18', email:'song18', password:111111)
u19 = User.create(username:'song19', email:'song19', password:111111)



w0 = Writer.create(name: 'John  Diamond', born: 'Earth', description: '')
w1 = Writer.create(name: 'Bill Watterson', born: 'Earth', description: '')
w2 = Writer.create(name: 'J.K. Rowling', born: 'Earth', description: '')
w3 = Writer.create(name: 'J.R.R. Tolkien', born: 'Earth', description: '')
w4 = Writer.create(name: 'Gary Russell', born: 'Earth', description: '')
w5 = Writer.create(name: 'Art Spiegelman', born: 'Earth', description: '')
w6 = Writer.create(name: 'Jane Austen', born: 'Earth', description: '')
w7 = Writer.create(name: 'Stephen King', born: 'Earth', description: '')
w8 = Writer.create(name: 'Arthur Bennett', born: 'Earth', description: '')
w9 = Writer.create(name: 'Robert A. Caro', born: 'Earth', description: '')
w10 = Writer.create(name: 'Audre Lorde', born: 'Earth', description: '')
w11 = Writer.create(name: 'Victor Villaseñor', born: 'Earth', description: '')
w12 = Writer.create(name: 'Arthur Conan Doyle', born: 'Earth', description: '')
w13 = Writer.create(name: 'J.R. Ward', born: 'Earth', description: '')
w14 = Writer.create(name: 'Diana Gabaldon', born: 'Earth', description: '')
w15 = Writer.create(name: 'Karen Kingsbury', born: 'Earth', description: '')
w16 = Writer.create(name: 'L.M. Montgomery', born: 'Earth', description: '')
w17 = Writer.create(name: 'Jim Butcher', born: 'Earth', description: '')
w18 = Writer.create(name: 'Stephen E. Ambrose', born: 'Earth', description: '')
w19 = Writer.create(name: 'Steven Pressfield', born: 'Earth', description: '')
w20 = Writer.create(name: 'Tite Kubo', born: 'Earth', description: '')
w21 = Writer.create(name: 'Raymond Carver', born: 'Earth', description: '')
w22 = Writer.create(name: 'James Herriot', born: 'Earth', description: '')
w23 = Writer.create(name: 'Shelby Foote', born: 'Earth', description: '')
w24 = Writer.create(name: 'William Manchester', born: 'Earth', description: '')
w25 = Writer.create(name: 'Maya Angelou', born: 'Earth', description: '')
w26 = Writer.create(name: 'George R.R. Martin', born: 'Earth', description: '')
w27 = Writer.create(name: 'Herman Wouk', born: 'Earth', description: '')
w28 = Writer.create(name: 'Ray Bradbury', born: 'Earth', description: '')
w29 = Writer.create(name: 'Elisabeth Elliot', born: 'Earth', description: '')
w30 = Writer.create(name: 'David Eddings', born: 'Earth', description: '')
w31 = Writer.create(name: 'Brian Sibley', born: 'Earth', description: '')
w32 = Writer.create(name: 'Douglas Adams', born: 'Earth', description: '')
w33 = Writer.create(name: 'Edgar Allan Poe', born: 'Earth', description: '')
w34 = Writer.create(name: 'David James Duncan', born: 'Earth', description: '')
w35 = Writer.create(name: 'David Simon', born: 'Earth', description: '')
w36 = Writer.create(name: 'Ina May Gaskin', born: 'Earth', description: '')
w37 = Writer.create(name: 'Megan Whalen Turner', born: 'Earth', description: '')
w38 = Writer.create(name: 'Noah Gordon', born: 'Earth', description: '')
w39 = Writer.create(name: 'Colleen McCullough', born: 'Earth', description: '')
w40 = Writer.create(name: 'Frank Warren', born: 'Earth', description: '')
w41 = Writer.create(name: 'bell hooks', born: 'Earth', description: '')
w42 = Writer.create(name: 'Rohinton Mistry', born: 'Earth', description: '')
w43 = Writer.create(name: 'Jacqueline Carey', born: 'Earth', description: '')
w44 = Writer.create(name: 'Nancy Tillman', born: 'Earth', description: '')
w45 = Writer.create(name: 'Patrick OBrian', born: 'Earth', description: '')
w46 = Writer.create(name: 'Rumiko Takahashi', born: 'Earth', description: '')
w47 = Writer.create(name: 'Isaac Asimov', born: 'Earth', description: '')
w48 = Writer.create(name: 'Dr. Seuss', born: 'Earth', description: '')

b = Hash.new()
b[0] = Book.create(title:'The Diamond Color Meditation: Color Pathway to the Soul', isbn:'1890995525', language:'eng',   num_pages:'74', publish_at:'2/1/2006', house:'Square One Publishers', description:'The Diamond Color Meditation" presents an inspiring use of color in a therapeutic meditation designed for deep personal growth and healing. Includes a complete guide with color meditation plates, charts of herbs and homeopathic remedies and related acupuncture points. This book goes far beyond traditional color therapies and introduces a completely original and new concept in using color for healing. It is color therapy for a Higher Purpose: a way, a spiritual path, a Color Pathway to the Soul.',writer_id: w0.id)
b[1] = Book.create(title:'The Complete Calvin and Hobbes', isbn:'740748475', language:'eng',   num_pages:'1456', publish_at:'9/6/2005', house:'Andrews McMeel Publishing', description:'Calvin and Hobbes is unquestionably one of the most popular comic strips of all time. The imaginative world of a boy and his real-only-to-him tiger was first syndicated in 1985 and appeared in more than 2,400 newspapers when Bill Watterson retired on January 1, 1996. The entire body of Calvin and Hobbes cartoons published in a truly noteworthy tribute to this singular cartoon in The Complete Calvin and Hobbes. Composed of three hardcover, four-color volumes in a sturdy slipcase, this New York Times best-selling edition includes all Calvin and Hobbes cartoons that ever appeared in syndication. This is the treasure that all Calvin and Hobbes fans seek',writer_id: w1.id)
b[2] = Book.create(title:'Its a Magical World (Calvin and Hobbes  No.11)', isbn:'836221362', language:'eng',   num_pages:'176', publish_at:'9/1/1996', house:'Andrews McMeel Publishing', description:'When cartoonist Bill Watterson announced that his phenomenally popular cartoon strip would be discontinued, Calvin and Hobbes fans throughout the world went into mourning. Fans have learned to survive -- despite the absence of the boy and his tiger in the daily newspaper. Its a Magical World delivers all the satisfaction of visiting its characters once more. Calvin fans will be able to see their favorite mischief maker stir it up with his furry friend, long-suffering parents, classmate Susie Derkins, school teacher Miss Wormwood, and Rosalyn the baby-sitter. Its a Magical World includes full-color Sundays and has it all: Calvin-turned-firefly waking Hobbes with his flashlight glow; courageous Spaceman Spiff rocketing through alien galaxies as he battles Dad-turned-Bug-Being; and Calvins always inspired snowman art. Theres no better way for Watterson fans to savor again the special qualities of their favorite strip',writer_id: w1.id)
b[3] = Book.create(title:'Harry Potter Collection (Harry Potter No.1-6)', isbn:'439827604', language:'eng',   num_pages:'3342', publish_at:'9/12/2005', house:'Scholastic', description:'Description',writer_id: w2.id)
b[4] = Book.create(title:'Homicidal Psycho Jungle Cat (Calvin and Hobbes No.9)', isbn:'836217691', language:'eng',   num_pages:'176', publish_at:'9/6/1994', house:'Andrews McMeel Publishing', description:'Description',writer_id: w1.id)
b[5] = Book.create(title:'The Days Are Just Packed', isbn:'836217357', language:'eng',   num_pages:'176', publish_at:'9/1/1993', house:'Andrews McMeel Publishing', description:'Description',writer_id: w1.id)
b[6] = Book.create(title:'The Calvin and Hobbes Tenth Anniversary Book', isbn:'836204387', language:'eng',   num_pages:'208', publish_at:'9/5/1995', house:'Andrews McMeel Publishing', description:'Many moons ago, the magic of Calvin and Hobbes first appeared on the funny pages and the world was introduced to a wondrous pair of friends -- a boy and his tiger, who brought new life to the comics page. To celebrate the tenth anniversary of this distinguished partnership, Bill Watterson prepared this special book, sharing his thoughts on cartooning and creating Calvin and Hobbes, illustrated throughout with favorite black-and-white and color cartoons.',writer_id: w1.id)
b[7] = Book.create(title:'J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings', isbn:'345538374', language:'eng',   num_pages:'1728', publish_at:'9/25/2012', house:'Ballantine Books', description:'Description',writer_id: w3.id)
b[8] = Book.create(title:'The Lord of the Rings: The Art of the Fellowship of the Ring', isbn:'618212906', language:'eng',   num_pages:'192', publish_at:'6/12/2002', house:'Houghton Mifflin Harcourt', description:'Description',writer_id: w4.id)
b[9] = Book.create(title:'Harry Potter and the Goblet of Fire (Harry Potter  No.4)', isbn:'074754624X', language:'eng',   num_pages:'636', publish_at:'7/8/2000', house:'Bloomsbury', description:'Description',writer_id: w2.id)
b[10] = Book.create(title:'The Complete Maus', isbn:'141014083', language:'eng',   num_pages:'296', publish_at:'10/2/2003', house:'Penguin Books', description:'Description',writer_id: w5.id)
b[11] = Book.create(title:'The Complete Novels', isbn:'140259449', language:'eng',   num_pages:'1344', publish_at:'6/17/1996', house:'Penguin', description:'Description',writer_id: w6.id)
b[12] = Book.create(title:'Carrie / Salems Lot / The Shining', isbn:'517219026', language:'eng',   num_pages:'1096', publish_at:'7/2/2002', house:'Wings', description:'Description',writer_id: w7.id)
b[13] = Book.create(title:'The Valley of Vision: A Collection of Puritan Prayers and Devotions', isbn:'851512283', language:'eng',   num_pages:'223', publish_at:'11/1/1975', house:'Banner of Truth', description:'Description',writer_id: w8.id)
b[14] = Book.create(title:'The Power Broker: Robert Moses and the Fall of New York', isbn:'394720245', language:'eng',   num_pages:'1344', publish_at:'7/12/1975', house:'Vintage', description:'Description',writer_id: w9.id)
b[15] = Book.create(title:'Sister Outsider: Essays and Speeches', isbn:'895941414', language:'en-GB',   num_pages:'190', publish_at:'6/1/1984', house:'Crossing Press', description:'Description',writer_id: w10.id)
b[16] = Book.create(title:'Harry Potter y la Orden del Fénix (Harry Potter  No.5)', isbn:'8478888845', language:'spa',   num_pages:'893', publish_at:'2/21/2004', house:'Emece Editores', description:'Description',writer_id: w2.id)
b[17] = Book.create(title:'Rain of Gold', isbn:'038531177X', language:'eng',   num_pages:'576', publish_at:'9/1/1992', house:'Delta', description:'Description',writer_id: w11.id)
b[18] = Book.create(title:'Sherlock Holmes: The Complete Novels and Stories  Volume I', isbn:'553212419', language:'eng',   num_pages:'1059', publish_at:'8/26/1986', house:'Bantam Classics', description:'Description',writer_id: w12.id)
b[19] = Book.create(title:'Lover Awakened (Black Dagger Brotherhood  No.3)', isbn:'451219368', language:'eng',   num_pages:'448', publish_at:'9/5/2006', house:'Signet', description:'Description',writer_id: w13.id)
b[20] = Book.create(title:'The Green Mile', isbn:'451933028', language:'eng',   num_pages:'592', publish_at:'9/1/1996', house:'Penguin Signet', description:'Description',writer_id: w7.id)
b[21] = Book.create(title:'A Breath of Snow and Ashes (Outlander  No.6)', isbn:'385340397', language:'eng',   num_pages:'980', publish_at:'8/29/2006', house:'Delta', description:'Description',writer_id: w14.id)
b[22] = Book.create(title:'Found (Firstborn  No.3)', isbn:'842387455', language:'eng',   num_pages:'342', publish_at:'8/1/2006', house:'Tyndale House Publishers', description:'Description',writer_id: w15.id)
b[23] = Book.create(title:'The Complete Anne of Green Gables Boxed Set (Anne of Green Gables  No.1-8)', isbn:'553609416', language:'eng',   num_pages:'2088', publish_at:'10/6/1998', house:'Starfire', description:'Description',writer_id: w16.id)
b[24] = Book.create(title:'Dead Beat (The Dresden Files  No.7)', isbn:'045146091X', language:'eng',   num_pages:'517', publish_at:'1/1/2006', house:'Roc', description:'Description',writer_id: w17.id)
b[25] = Book.create(title:'Band of Brothers: E Company  506th Regiment  101st Airborne from Normandy to Hitlers Eagles Nest', isbn:'743464117', language:'eng',   num_pages:'432', publish_at:'9/1/2002', house:'Simon & Schuster; Media Tie-In edition', description:'Description',writer_id: w18.id)
b[26] = Book.create(title:'Forever (Firstborn  No.5)', isbn:'1414307640', language:'eng',   num_pages:'346', publish_at:'2/22/2007', house:'Tyndale House Publishers', description:'Description',writer_id: w15.id)
b[27] = Book.create(title:'Gates of Fire', isbn:'055338368X', language:'eng',   num_pages:'392', publish_at:'9/27/2005', house:'Bantam', description:'Description',writer_id: w19.id)
b[28] = Book.create(title:'Bleach  Volume 15', isbn:'1421506130', language:'eng',   num_pages:'208', publish_at:'10/3/2006', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[29] = Book.create(title:'Where Im Calling From: New and Selected Stories', isbn:'679722319', language:'eng',   num_pages:'544', publish_at:'9/12/2000', house:'Vintage Contemporaries', description:'Description',writer_id: w21.id)
b[30] = Book.create(title:'The Lord God Made Them All', isbn:'312966202', language:'eng',   num_pages:'373', publish_at:'9/15/1998', house:'St. Martins Paperbacks', description:'Description',writer_id: w22.id)
b[31] = Book.create(title:'The Civil War  Vol. 1: Fort Sumter to Perryville', isbn:'394746236', language:'eng',   num_pages:'856', publish_at:'11/12/1986', house:'Vintage', description:'Description',writer_id: w23.id)
b[32] = Book.create(title:'The Last Lion: Winston Spencer Churchill: Visions of Glory 1874-1932', isbn:'385313489', language:'eng',   num_pages:'992', publish_at:'4/1/1984', house:'Delta', description:'Description',writer_id: w24.id)
b[33] = Book.create(title:'Family (Firstborn  No.4)', isbn:'842387463', language:'eng',   num_pages:'345', publish_at:'10/1/2006', house:'Tyndale House Publishers', description:'Description',writer_id: w15.id)
b[34] = Book.create(title:'The Complete Collected Poems', isbn:'067942895X', language:'eng',   num_pages:'273', publish_at:'9/13/1994', house:'Random House', description:'Description',writer_id: w25.id)
b[35] = Book.create(title:'Harry Potter and the Chamber of Secrets (Harry Potter  No.2)', isbn:'439554896', language:'eng',   num_pages:'352', publish_at:'11/1/2003', house:'Scholastic', description:'Description',writer_id: w2.id)
b[36] = Book.create(title:'A Clash of Kings  (A Song of Ice and Fire  No.2)', isbn:'553381695', language:'eng',   num_pages:'969', publish_at:'5/28/2002', house:'Bantam', description:'Description',writer_id: w26.id)
b[37] = Book.create(title:'War and Remembrance (The Henry Family  No.2)', isbn:'316954993', language:'eng',   num_pages:'1042', publish_at:'2/5/2002', house:'Back Bay Books', description:'Description',writer_id: w27.id)
b[38] = Book.create(title:'All Things Wise and Wonderful', isbn:'312335288', language:'eng',   num_pages:'448', publish_at:'11/1/2004', house:'St. Martins Griffin', description:'Description',writer_id: w22.id)
b[39] = Book.create(title:'Forgiven (Firstborn  No.2)', isbn:'842387447', language:'eng',   num_pages:'358', publish_at:'9/23/2005', house:'Tyndale House Publishers', description:'Description',writer_id: w15.id)
b[40] = Book.create(title:'Bradbury Stories: 100 of His Most Celebrated Tales', isbn:'60544880', language:'eng',   num_pages:'912', publish_at:'4/5/2005', house:'William Morrow Paperbacks', description:'Description',writer_id: w28.id)
b[41] = Book.create(title:'Harry Potter Schoolbooks Box Set: Two Classic Books from the Library of Hogwarts School of Witchcraft and Wizardry', isbn:'043932162X', language:'eng',   num_pages:'240', publish_at:'11/1/2001', house:'Arthur A. Levine', description:'Description',writer_id: w2.id)
b[42] = Book.create(title:'Shadow of the Almighty: The Life and Testament of Jim Elliot', isbn:'006062213X', language:'eng',   num_pages:'272', publish_at:'9/29/2009', house:'HarperOne', description:'Description',writer_id: w29.id)
b[43] = Book.create(title:'Voyager (Outlander  No.3)', isbn:'385335997', language:'eng',   num_pages:'870', publish_at:'8/7/2001', house:'Delta', description:'Description',writer_id: w14.id)
b[44] = Book.create(title:'The Belgariad  Vol. Two: Castle of Wizardry / Enchanters End Game (The Belgariad  No.4-5)', isbn:'345456319', language:'eng',   num_pages:'483', publish_at:'8/27/2002', house:'Del Rey', description:'Description',writer_id: w30.id)
b[45] = Book.create(title:'The Lord of the Rings: Official Movie Guide', isbn:'618154027', language:'eng',   num_pages:'120', publish_at:'11/6/2001', house:'Houghton Mifflin Harcourt', description:'Description',writer_id: w31.id)
b[46] = Book.create(title:'The Ultimate Hitchhikers Guide to the Galaxy (Hitchhikers Guide to the Galaxy  No.1-5)', isbn:'345453743', language:'eng',   num_pages:'815', publish_at:'4/30/2002', house:'Del Rey Books', description:'Description',writer_id: w32.id)
b[47] = Book.create(title:'The Complete Stories and Poems', isbn:'385074077', language:'eng',   num_pages:'821', publish_at:'8/15/1984', house:'Doubleday & Company  Inc.', description:'Description',writer_id: w33.id)
b[48] = Book.create(title:'The Brothers K', isbn:'055337849X', language:'eng',   num_pages:'645', publish_at:'6/1/1996', house:'Dial Press Trade Paperback', description:'Description',writer_id: w34.id)
b[49] = Book.create(title:'Homicide: A Year on the Killing Streets', isbn:'805080759', language:'eng',   num_pages:'646', publish_at:'8/22/2006', house:'Holt McDougal', description:'Description',writer_id: w35.id)
b[50] = Book.create(title:'Bleach  Volume 14', isbn:'1421506122', language:'eng',   num_pages:'208', publish_at:'8/1/2006', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[51] = Book.create(title:'Spiritual Midwifery', isbn:'1570671044', language:'eng',   num_pages:'482', publish_at:'1/1/2002', house:'Book Publishing Company (TN)', description:'Description',writer_id: w36.id)
b[52] = Book.create(title:'The Winds of War (The Henry Family  No.1)', isbn:'316952664', language:'eng',   num_pages:'896', publish_at:'2/5/2002', house:'Back Bay Books', description:'Description',writer_id: w27.id)
b[53] = Book.create(title:'The King of Attolia (The Queens Thief  No.3)', isbn:'006083577X', language:'eng',   num_pages:'387', publish_at:'1/24/2006', house:'Greenwillow Books', description:'Description',writer_id: w37.id)
b[54] = Book.create(title:'The Physician (Cole Family Trilogy  No.1)', isbn:'751503894', language:'eng',   num_pages:'720', publish_at:'7/1/2001', house:'Little  Brown Book Group', description:'Description',writer_id: w38.id)
b[55] = Book.create(title:'Caesar (Masters of Rome  No.5)', isbn:'60510854', language:'eng',   num_pages:'928', publish_at:'1/28/2003', house:'Avon', description:'Description',writer_id: w39.id)
b[56] = Book.create(title:'The Secret Lives of Men and Women: A PostSecret Book', isbn:'61198757', language:'en-GB',   num_pages:'144', publish_at:'1/9/2007', house:'William Morrow', description:'Description',writer_id: w40.id)
b[57] = Book.create(title:'Teaching to Transgress: Education as the Practice of Freedom', isbn:'415908086', language:'eng',   num_pages:'216', publish_at:'9/14/1994', house:'Routledge', description:'Description',writer_id: w41.id)
b[58] = Book.create(title:'The Fellowship of the Ring (The Lord of the Rings  No.1)', isbn:'618346252', language:'eng',   num_pages:'398', publish_at:'9/5/2003', house:'Houghton Mifflin Harcourt', description:'Description',writer_id: w3.id)
b[59] = Book.create(title:'A Fine Balance', isbn:'140003065X', language:'eng',   num_pages:'603', publish_at:'11/30/2001', house:'Vintage', description:'Description',writer_id: w42.id)
b[60] = Book.create(title:'Cursors Fury (Codex Alera  No.3)', isbn:'441014348', language:'eng',   num_pages:'442', publish_at:'12/5/2006', house:'Ace Hardcover', description:'Description',writer_id: w17.id)
b[61] = Book.create(title:'Kushiels Avatar (Phèdres Trilogy  No.3)', isbn:'1405034149', language:'eng',   num_pages:'702', publish_at:'9/17/2004', house:'Tor', description:'Description',writer_id: w43.id)
b[62] = Book.create(title:'On the Night You Were Born', isbn:'312346069', language:'en-US',   num_pages:'32', publish_at:'10/17/2006', house:'Feiwel & Friends', description:'Description',writer_id: w44.id)
b[63] = Book.create(title:'Bleach  Volume 12', isbn:'1421504030', language:'eng',   num_pages:'208', publish_at:'4/4/2006', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[64] = Book.create(title:'Bleach  Volume 11', isbn:'1421502712', language:'eng',   num_pages:'208', publish_at:'2/7/2006', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[65] = Book.create(title:'Bleach  Volume 13', isbn:'1421506114', language:'eng',   num_pages:'208', publish_at:'6/6/2006', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[66] = Book.create(title:'The Truelove (Aubrey & Maturin No.15)', isbn:'393310167', language:'eng',   num_pages:'304', publish_at:'7/17/1993', house:'W. W. Norton  Company', description:'Description',writer_id: w45.id)
b[67] = Book.create(title:'Bleach  Volume 19', isbn:'142151043X', language:'eng',   num_pages:'216', publish_at:'6/5/2007', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[68] = Book.create(title:'The Adventures of Sherlock Holmes', isbn:'1842055062', language:'eng',   num_pages:'189', publish_at:'1/1/2004', house:'Geddes & Grosset', description:'Description',writer_id: w12.id)
b[69] = Book.create(title:'InuYasha Ani-Manga  Vol. 1 (Inuyasha Ani-Manga  No.1)', isbn:'1591162025', language:'eng',   num_pages:'206', publish_at:'1/14/2004', house:'VIZ Media LLC', description:'Description',writer_id: w46.id)
b[70] = Book.create(title:'Bleach  Volume 20', isbn:'1421510448', language:'eng',   num_pages:'216', publish_at:'8/7/2007', house:'VIZ Media LLC', description:'Description',writer_id: w20.id)
b[71] = Book.create(title:'The Malloreon  Vol. 2: Sorceress of Darshiva / The Seeress of Kell (The Malloreon  No.4-5)', isbn:'345483871', language:'eng',   num_pages:'528', publish_at:'8/30/2005', house:'Del Rey', description:'Description',writer_id: w30.id)
b[72] = Book.create(title:'The Complete Stories  Vol 1', isbn:'038541627X', language:'eng',   num_pages:'624', publish_at:'10/1/1990', house:'Broadway', description:'Description',writer_id: w47.id)
b[73] = Book.create(title:'The Lorax', isbn:'679889108', language:'eng',   num_pages:'72', publish_at:'2/24/1998', house:'Random House Books for Young Readers', description:'Description',writer_id: w48.id)



    b.keys.each do |no|
        file = open("https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/#{no}.jpg")
        b[no].cover.attach(io:file, filename: "#{no}.jpg")
    end
        # file2 = open("https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/73.jpg")
        # b[73].cover.attach(io:file2, filename: "73.jpg")

        # file0 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/0.jpg')
        # b[0].cover.attach(io:file0, filename: '0.jpg')
        # file1 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/1.jpg')
        # b[1].cover.attach(io:file1, filename: '1.jpg')
        # file2 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/2.jpg')
        # b[2].cover.attach(io:file2, filename: '2.jpg')
        # file3 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/3.jpg')
        # b[3].cover.attach(io:file3, filename: '3.jpg')
        # file4 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/4.jpg')
        # b[4].cover.attach(io:file4, filename: '4.jpg')
        # file5 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/5.jpg')
        # b[5].cover.attach(io:file5, filename: '5.jpg')
        # file6 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/6.jpg')
        # b[6].cover.attach(io:file6, filename: '6.jpg')
        # file7 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/7.jpg')
        # b[7].cover.attach(io:file7, filename: '7.jpg')
        # file8 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/8.jpg')
        # b[8].cover.attach(io:file8, filename: '8.jpg')
        # file9 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/9.jpg')
        # b[9].cover.attach(io:file9, filename: '9.jpg')
        # file10 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/10.jpg')
        # b[10].cover.attach(io:file10, filename: '10.jpg')
        # file11 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/11.jpg')
        # b[11].cover.attach(io:file11, filename: '11.jpg')
        # file12 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/12.jpg')
        # b[12].cover.attach(io:file12, filename: '12.jpg')
        # file13 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/13.jpg')
        # b[13].cover.attach(io:file13, filename: '13.jpg')
        # file14 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/14.jpg')
        # b[14].cover.attach(io:file14, filename: '14.jpg')
        # file15 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/15.jpg')
        # b[15].cover.attach(io:file15, filename: '15.jpg')
        # file16 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/16.jpg')
        # b[16].cover.attach(io:file16, filename: '16.jpg')
        # file17 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/17.jpg')
        # b[17].cover.attach(io:file17, filename: '17.jpg')
        # file18 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/18.jpg')
        # b[18].cover.attach(io:file18, filename: '18.jpg')
        # file19 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/19.jpg')
        # b[19].cover.attach(io:file19, filename: '19.jpg')
        # file20 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/20.jpg')
        # b[20].cover.attach(io:file20, filename: '20.jpg')
        # file21 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/21.jpg')
        # b[21].cover.attach(io:file21, filename: '21.jpg')
        # file22 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/22.jpg')
        # b[22].cover.attach(io:file22, filename: '22.jpg')
        # file23 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/23.jpg')
        # b[23].cover.attach(io:file23, filename: '23.jpg')
        # file24 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/24.jpg')
        # b[24].cover.attach(io:file24, filename: '24.jpg')
        # file25 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/25.jpg')
        # b[25].cover.attach(io:file25, filename: '25.jpg')
        # file26 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/26.jpg')
        # b[26].cover.attach(io:file26, filename: '26.jpg')
        # file27 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/27.jpg')
        # b[27].cover.attach(io:file27, filename: '27.jpg')
        # file28 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/28.jpg')
        # b[28].cover.attach(io:file28, filename: '28.jpg')
        # file29 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/29.jpg')
        # b[29].cover.attach(io:file29, filename: '29.jpg')
        # file30 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/30.jpg')
        # b[30].cover.attach(io:file30, filename: '30.jpg')
        # file31 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/31.jpg')
        # b[31].cover.attach(io:file31, filename: '31.jpg')
        # file32 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/32.jpg')
        # b[32].cover.attach(io:file32, filename: '32.jpg')
        # file33 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/33.jpg')
        # b[33].cover.attach(io:file33, filename: '33.jpg')
        # file34 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/34.jpg')
        # b[34].cover.attach(io:file34, filename: '34.jpg')
        # file35 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/35.jpg')
        # b[35].cover.attach(io:file35, filename: '35.jpg')
        # file36 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/36.jpg')
        # b[36].cover.attach(io:file36, filename: '36.jpg')
        # file37 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/37.jpg')
        # b[37].cover.attach(io:file37, filename: '37.jpg')
        # file38 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/38.jpg')
        # b[38].cover.attach(io:file38, filename: '38.jpg')
        # file39 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/39.jpg')
        # b[39].cover.attach(io:file39, filename: '39.jpg')
        # file40 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/40.jpg')
        # b[40].cover.attach(io:file40, filename: '40.jpg')
        # file41 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/41.jpg')
        # b[41].cover.attach(io:file41, filename: '41.jpg')
        # file42 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/42.jpg')
        # b[42].cover.attach(io:file42, filename: '42.jpg')
        # file43 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/43.jpg')
        # b[43].cover.attach(io:file43, filename: '43.jpg')
        # file44 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/44.jpg')
        # b[44].cover.attach(io:file44, filename: '44.jpg')
        # file45 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/45.jpg')
        # b[45].cover.attach(io:file45, filename: '45.jpg')
        # file46 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/46.jpg')
        # b[46].cover.attach(io:file46, filename: '46.jpg')
        # file47 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/47.jpg')
        # b[47].cover.attach(io:file47, filename: '47.jpg')
        # file48 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/48.jpg')
        # b[48].cover.attach(io:file48, filename: '48.jpg')
        # file49 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/49.jpg')
        # b[49].cover.attach(io:file49, filename: '49.jpg')
        # file50 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/50.jpg')
        # b[50].cover.attach(io:file50, filename: '50.jpg')
        # file51 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/51.jpg')
        # b[51].cover.attach(io:file51, filename: '51.jpg')
        # file52 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/52.jpg')
        # b[52].cover.attach(io:file52, filename: '52.jpg')
        # file53 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/53.jpg')
        # b[53].cover.attach(io:file53, filename: '53.jpg')
        # file54 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/54.jpg')
        # b[54].cover.attach(io:file54, filename: '54.jpg')
        # file55 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/55.jpg')
        # b[55].cover.attach(io:file55, filename: '55.jpg')
        # file56 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/56.jpg')
        # b[56].cover.attach(io:file56, filename: '56.jpg')
        # file57 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/57.jpg')
        # b[57].cover.attach(io:file57, filename: '57.jpg')
        # file58 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/58.jpg')
        # b[58].cover.attach(io:file58, filename: '58.jpg')
        # file59 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/59.jpg')
        # b[59].cover.attach(io:file59, filename: '59.jpg')
        # file60 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/60.jpg')
        # b[60].cover.attach(io:file60, filename: '60.jpg')
        # file61 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/61.jpg')
        # b[61].cover.attach(io:file61, filename: '61.jpg')
        # file62 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/62.jpg')
        # b[62].cover.attach(io:file62, filename: '62.jpg')
        # file63 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/63.jpg')
        # b[63].cover.attach(io:file63, filename: '63.jpg')
        # file64 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/64.jpg')
        # b[64].cover.attach(io:file64, filename: '64.jpg')
        # file65 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/65.jpg')
        # b[65].cover.attach(io:file65, filename: '65.jpg')
        # file66 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/66.jpg')
        # b[66].cover.attach(io:file66, filename: '66.jpg')
        # file67 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/67.jpg')
        # b[67].cover.attach(io:file67, filename: '67.jpg')
        # file68 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/68.jpg')
        # b[68].cover.attach(io:file68, filename: '68.jpg')
        # file69 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/69.jpg')
        # b[69].cover.attach(io:file69, filename: '69.jpg')
        # file70 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/70.jpg')
        # b[70].cover.attach(io:file70, filename: '70.jpg')
        # file71 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/71.jpg')
        # b[71].cover.attach(io:file71, filename: '71.jpg')
        # file72 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/72.jpg')
        # b[72].cover.attach(io:file72, filename: '72.jpg')
        # file73 = open('https://lovereads-dev.s3-us-west-1.amazonaws.com/covers/73.jpg')
        # b[73].cover.attach(io:file73, filename: '73.jpg')

r0 = Review.create(user_id: u0.id, book_id:b[7].id, rate: 2)
r1 = Review.create(user_id: u0.id, book_id:b[15].id, rate: 1)
r2 = Review.create(user_id: u0.id, book_id:b[26].id, rate: 1)
r3 = Review.create(user_id: u0.id, book_id:b[35].id, rate: 5)
r4 = Review.create(user_id: u0.id, book_id:b[40].id, rate: 3)
r5 = Review.create(user_id: u0.id, book_id:b[53].id, rate: 1)
r6 = Review.create(user_id: u0.id, book_id:b[68].id, rate: 4)
r7 = Review.create(user_id: u1.id, book_id:b[0].id, rate: 4)
r8 = Review.create(user_id: u1.id, book_id:b[16].id, rate: 4)
r9 = Review.create(user_id: u1.id, book_id:b[27].id, rate: 4)
r10 = Review.create(user_id: u1.id, book_id:b[37].id, rate: 1)
r11 = Review.create(user_id: u1.id, book_id:b[45].id, rate: 2)
r12 = Review.create(user_id: u1.id, book_id:b[57].id, rate: 4)
r13 = Review.create(user_id: u1.id, book_id:b[61].id, rate: 5)
r14 = Review.create(user_id: u2.id, book_id:b[8].id, rate: 3)
r15 = Review.create(user_id: u2.id, book_id:b[15].id, rate: 3)
r16 = Review.create(user_id: u2.id, book_id:b[26].id, rate: 2)
r17 = Review.create(user_id: u2.id, book_id:b[35].id, rate: 1)
r18 = Review.create(user_id: u2.id, book_id:b[40].id, rate: 2)
r19 = Review.create(user_id: u2.id, book_id:b[58].id, rate: 5)
r20 = Review.create(user_id: u2.id, book_id:b[65].id, rate: 4)
r21 = Review.create(user_id: u3.id, book_id:b[1].id, rate: 4)
r22 = Review.create(user_id: u3.id, book_id:b[14].id, rate: 4)
r23 = Review.create(user_id: u3.id, book_id:b[24].id, rate: 2)
r24 = Review.create(user_id: u3.id, book_id:b[31].id, rate: 1)
r25 = Review.create(user_id: u3.id, book_id:b[42].id, rate: 2)
r26 = Review.create(user_id: u3.id, book_id:b[53].id, rate: 1)
r27 = Review.create(user_id: u3.id, book_id:b[67].id, rate: 2)
r28 = Review.create(user_id: u4.id, book_id:b[0].id, rate: 2)
r29 = Review.create(user_id: u4.id, book_id:b[18].id, rate: 3)
r30 = Review.create(user_id: u4.id, book_id:b[22].id, rate: 3)
r31 = Review.create(user_id: u4.id, book_id:b[31].id, rate: 5)
r32 = Review.create(user_id: u4.id, book_id:b[41].id, rate: 4)
r33 = Review.create(user_id: u4.id, book_id:b[55].id, rate: 5)
r34 = Review.create(user_id: u4.id, book_id:b[62].id, rate: 4)
r35 = Review.create(user_id: u5.id, book_id:b[4].id, rate: 2)
r36 = Review.create(user_id: u5.id, book_id:b[14].id, rate: 2)
r37 = Review.create(user_id: u5.id, book_id:b[21].id, rate: 2)
r38 = Review.create(user_id: u5.id, book_id:b[39].id, rate: 4)
r39 = Review.create(user_id: u5.id, book_id:b[44].id, rate: 4)
r40 = Review.create(user_id: u5.id, book_id:b[59].id, rate: 2)
r41 = Review.create(user_id: u5.id, book_id:b[60].id, rate: 5)
r42 = Review.create(user_id: u6.id, book_id:b[0].id, rate: 4)
r43 = Review.create(user_id: u6.id, book_id:b[12].id, rate: 5)
r44 = Review.create(user_id: u6.id, book_id:b[25].id, rate: 4)
r45 = Review.create(user_id: u6.id, book_id:b[32].id, rate: 5)
r46 = Review.create(user_id: u6.id, book_id:b[43].id, rate: 5)
r47 = Review.create(user_id: u6.id, book_id:b[54].id, rate: 1)
r48 = Review.create(user_id: u6.id, book_id:b[69].id, rate: 3)
r49 = Review.create(user_id: u7.id, book_id:b[1].id, rate: 3)
r50 = Review.create(user_id: u7.id, book_id:b[19].id, rate: 2)
r51 = Review.create(user_id: u7.id, book_id:b[21].id, rate: 1)
r52 = Review.create(user_id: u7.id, book_id:b[37].id, rate: 3)
r53 = Review.create(user_id: u7.id, book_id:b[43].id, rate: 5)
r54 = Review.create(user_id: u7.id, book_id:b[52].id, rate: 3)
r55 = Review.create(user_id: u7.id, book_id:b[63].id, rate: 1)
r56 = Review.create(user_id: u8.id, book_id:b[8].id, rate: 2)
r57 = Review.create(user_id: u8.id, book_id:b[16].id, rate: 4)
r58 = Review.create(user_id: u8.id, book_id:b[28].id, rate: 1)
r59 = Review.create(user_id: u8.id, book_id:b[33].id, rate: 5)
r60 = Review.create(user_id: u8.id, book_id:b[44].id, rate: 3)
r61 = Review.create(user_id: u8.id, book_id:b[53].id, rate: 3)
r62 = Review.create(user_id: u8.id, book_id:b[60].id, rate: 5)
r63 = Review.create(user_id: u9.id, book_id:b[0].id, rate: 5)
r64 = Review.create(user_id: u9.id, book_id:b[16].id, rate: 2)
r65 = Review.create(user_id: u9.id, book_id:b[20].id, rate: 3)
r66 = Review.create(user_id: u9.id, book_id:b[38].id, rate: 5)
r67 = Review.create(user_id: u9.id, book_id:b[41].id, rate: 5)
r68 = Review.create(user_id: u9.id, book_id:b[56].id, rate: 5)
r69 = Review.create(user_id: u9.id, book_id:b[65].id, rate: 4)
r70 = Review.create(user_id: u10.id, book_id:b[9].id, rate: 5)
r71 = Review.create(user_id: u10.id, book_id:b[14].id, rate: 3)
r72 = Review.create(user_id: u10.id, book_id:b[23].id, rate: 5)
r73 = Review.create(user_id: u10.id, book_id:b[30].id, rate: 4)
r74 = Review.create(user_id: u10.id, book_id:b[48].id, rate: 4)
r75 = Review.create(user_id: u10.id, book_id:b[53].id, rate: 5)
r76 = Review.create(user_id: u10.id, book_id:b[61].id, rate: 1)
r77 = Review.create(user_id: u11.id, book_id:b[8].id, rate: 2)
r78 = Review.create(user_id: u11.id, book_id:b[13].id, rate: 3)
r79 = Review.create(user_id: u11.id, book_id:b[26].id, rate: 4)
r80 = Review.create(user_id: u11.id, book_id:b[38].id, rate: 3)
r81 = Review.create(user_id: u11.id, book_id:b[49].id, rate: 5)
r82 = Review.create(user_id: u11.id, book_id:b[57].id, rate: 5)
r83 = Review.create(user_id: u11.id, book_id:b[66].id, rate: 3)
r84 = Review.create(user_id: u12.id, book_id:b[6].id, rate: 5)
r85 = Review.create(user_id: u12.id, book_id:b[11].id, rate: 4)
r86 = Review.create(user_id: u12.id, book_id:b[22].id, rate: 4)
r87 = Review.create(user_id: u12.id, book_id:b[36].id, rate: 5)
r88 = Review.create(user_id: u12.id, book_id:b[43].id, rate: 4)
r89 = Review.create(user_id: u12.id, book_id:b[57].id, rate: 5)
r90 = Review.create(user_id: u12.id, book_id:b[65].id, rate: 1)
r91 = Review.create(user_id: u13.id, book_id:b[8].id, rate: 3)
r92 = Review.create(user_id: u13.id, book_id:b[11].id, rate: 5)
r93 = Review.create(user_id: u13.id, book_id:b[28].id, rate: 3)
r94 = Review.create(user_id: u13.id, book_id:b[37].id, rate: 2)
r95 = Review.create(user_id: u13.id, book_id:b[42].id, rate: 1)
r96 = Review.create(user_id: u13.id, book_id:b[50].id, rate: 5)
r97 = Review.create(user_id: u13.id, book_id:b[66].id, rate: 4)
r98 = Review.create(user_id: u14.id, book_id:b[6].id, rate: 3)
r99 = Review.create(user_id: u14.id, book_id:b[18].id, rate: 3)
r100 = Review.create(user_id: u14.id, book_id:b[24].id, rate: 4)
r101 = Review.create(user_id: u14.id, book_id:b[39].id, rate: 4)
r102 = Review.create(user_id: u14.id, book_id:b[42].id, rate: 4)
r103 = Review.create(user_id: u14.id, book_id:b[54].id, rate: 2)
r104 = Review.create(user_id: u14.id, book_id:b[66].id, rate: 3)
r105 = Review.create(user_id: u15.id, book_id:b[5].id, rate: 1)
r106 = Review.create(user_id: u15.id, book_id:b[19].id, rate: 4)
r107 = Review.create(user_id: u15.id, book_id:b[26].id, rate: 2)
r108 = Review.create(user_id: u15.id, book_id:b[36].id, rate: 3)
r109 = Review.create(user_id: u15.id, book_id:b[41].id, rate: 1)
r110 = Review.create(user_id: u15.id, book_id:b[59].id, rate: 5)
r111 = Review.create(user_id: u15.id, book_id:b[61].id, rate: 1)
r112 = Review.create(user_id: u16.id, book_id:b[2].id, rate: 2)
r113 = Review.create(user_id: u16.id, book_id:b[11].id, rate: 2)
r114 = Review.create(user_id: u16.id, book_id:b[27].id, rate: 2)
r115 = Review.create(user_id: u16.id, book_id:b[37].id, rate: 2)
r116 = Review.create(user_id: u16.id, book_id:b[40].id, rate: 5)
r117 = Review.create(user_id: u16.id, book_id:b[51].id, rate: 4)
r118 = Review.create(user_id: u16.id, book_id:b[66].id, rate: 5)
r119 = Review.create(user_id: u17.id, book_id:b[4].id, rate: 4)
r120 = Review.create(user_id: u17.id, book_id:b[17].id, rate: 5)
r121 = Review.create(user_id: u17.id, book_id:b[29].id, rate: 5)
r122 = Review.create(user_id: u17.id, book_id:b[30].id, rate: 5)
r123 = Review.create(user_id: u17.id, book_id:b[44].id, rate: 2)
r124 = Review.create(user_id: u17.id, book_id:b[57].id, rate: 1)
r125 = Review.create(user_id: u17.id, book_id:b[63].id, rate: 3)
r126 = Review.create(user_id: u18.id, book_id:b[4].id, rate: 2)
r127 = Review.create(user_id: u18.id, book_id:b[14].id, rate: 3)
r128 = Review.create(user_id: u18.id, book_id:b[24].id, rate: 1)
r129 = Review.create(user_id: u18.id, book_id:b[31].id, rate: 5)
r130 = Review.create(user_id: u18.id, book_id:b[40].id, rate: 1)
r131 = Review.create(user_id: u18.id, book_id:b[56].id, rate: 3)
r132 = Review.create(user_id: u18.id, book_id:b[67].id, rate: 5)
r133 = Review.create(user_id: u19.id, book_id:b[5].id, rate: 1)
r134 = Review.create(user_id: u19.id, book_id:b[15].id, rate: 1)
r135 = Review.create(user_id: u19.id, book_id:b[20].id, rate: 4)
r136 = Review.create(user_id: u19.id, book_id:b[33].id, rate: 5)
r137 = Review.create(user_id: u19.id, book_id:b[43].id, rate: 5)
r138 = Review.create(user_id: u19.id, book_id:b[57].id, rate: 1)

t0 = Tag.create(name:'Biography')
t1 = Tag.create(name:'Business')
t2 = Tag.create(name:'Fiction')
t3 = Tag.create(name:'Graphic Novels')
t4 = Tag.create(name:'Historical Fiction')
t5 = Tag.create(name:'History')
t6 = Tag.create(name:'Mystery')
t7 = Tag.create(name:'Nonfiction')
t8 = Tag.create(name:'Poetry')
t9 = Tag.create(name:'Manga')
t10 = Tag.create(name:'Memoir')
t11 = Tag.create(name:'Music')
t12 = Tag.create(name:'Mystery')
t13 = Tag.create(name:'Nonfiction')
t14 = Tag.create(name:'Paranormal')
t15 = Tag.create(name:'Philosophy')
t16 = Tag.create(name:'Poetry')
t17 = Tag.create(name:'Psychology')
t18 = Tag.create(name:'Religion')
t19 = Tag.create(name:'Romance')
t20 = Tag.create(name:'Science')
t21 = Tag.create(name:'Science Fiction')
t22 = Tag.create(name:'Self Help')
t23 = Tag.create(name:'Suspense')
t24 = Tag.create(name:'Spirituality')
t25 = Tag.create(name:'Sports')
t26 = Tag.create(name:'Thriller')
t27 = Tag.create(name:'Travel')
t28 = Tag.create(name:'Young Adult')


Tagging.create( user_id:u0.id, book_id:b[73].id, tag_id:t28.id)
Tagging.create( user_id:u0.id, book_id:b[43].id, tag_id:t18.id)
Tagging.create( user_id:u0.id, book_id:b[37].id, tag_id:t11.id)
Tagging.create( user_id:u0.id, book_id:b[49].id, tag_id:t21.id)
Tagging.create( user_id:u0.id, book_id:b[16].id, tag_id:t24.id)
Tagging.create( user_id:u0.id, book_id:b[1].id, tag_id:t27.id)
Tagging.create( user_id:u0.id, book_id:b[33].id, tag_id:t3.id)
Tagging.create( user_id:u1.id, book_id:b[64].id, tag_id:t15.id)
Tagging.create( user_id:u1.id, book_id:b[33].id, tag_id:t1.id)
Tagging.create( user_id:u1.id, book_id:b[20].id, tag_id:t11.id)
Tagging.create( user_id:u1.id, book_id:b[19].id, tag_id:t23.id)
Tagging.create( user_id:u1.id, book_id:b[2].id, tag_id:t6.id)
Tagging.create( user_id:u1.id, book_id:b[32].id, tag_id:t9.id)
Tagging.create( user_id:u1.id, book_id:b[52].id, tag_id:t25.id)
Tagging.create( user_id:u2.id, book_id:b[57].id, tag_id:t2.id)
Tagging.create( user_id:u2.id, book_id:b[54].id, tag_id:t23.id)
Tagging.create( user_id:u2.id, book_id:b[46].id, tag_id:t23.id)
Tagging.create( user_id:u2.id, book_id:b[0].id, tag_id:t1.id)
Tagging.create( user_id:u2.id, book_id:b[73].id, tag_id:t28.id)
Tagging.create( user_id:u2.id, book_id:b[44].id, tag_id:t2.id)
Tagging.create( user_id:u2.id, book_id:b[43].id, tag_id:t16.id)
Tagging.create( user_id:u3.id, book_id:b[9].id, tag_id:t10.id)
Tagging.create( user_id:u3.id, book_id:b[28].id, tag_id:t25.id)
Tagging.create( user_id:u3.id, book_id:b[70].id, tag_id:t6.id)
Tagging.create( user_id:u3.id, book_id:b[5].id, tag_id:t25.id)
Tagging.create( user_id:u3.id, book_id:b[62].id, tag_id:t16.id)
Tagging.create( user_id:u3.id, book_id:b[44].id, tag_id:t1.id)
Tagging.create( user_id:u3.id, book_id:b[32].id, tag_id:t9.id)
Tagging.create( user_id:u4.id, book_id:b[65].id, tag_id:t11.id)
Tagging.create( user_id:u4.id, book_id:b[43].id, tag_id:t27.id)
Tagging.create( user_id:u4.id, book_id:b[46].id, tag_id:t12.id)
Tagging.create( user_id:u4.id, book_id:b[4].id, tag_id:t27.id)
Tagging.create( user_id:u4.id, book_id:b[48].id, tag_id:t25.id)
Tagging.create( user_id:u4.id, book_id:b[24].id, tag_id:t27.id)
Tagging.create( user_id:u4.id, book_id:b[2].id, tag_id:t13.id)
Tagging.create( user_id:u5.id, book_id:b[12].id, tag_id:t10.id)
Tagging.create( user_id:u5.id, book_id:b[61].id, tag_id:t0.id)
Tagging.create( user_id:u5.id, book_id:b[6].id, tag_id:t0.id)
Tagging.create( user_id:u5.id, book_id:b[73].id, tag_id:t8.id)
Tagging.create( user_id:u5.id, book_id:b[65].id, tag_id:t0.id)
Tagging.create( user_id:u5.id, book_id:b[14].id, tag_id:t14.id)
Tagging.create( user_id:u5.id, book_id:b[41].id, tag_id:t25.id)
Tagging.create( user_id:u6.id, book_id:b[22].id, tag_id:t23.id)
Tagging.create( user_id:u6.id, book_id:b[14].id, tag_id:t28.id)
Tagging.create( user_id:u6.id, book_id:b[44].id, tag_id:t17.id)
Tagging.create( user_id:u6.id, book_id:b[48].id, tag_id:t27.id)
Tagging.create( user_id:u6.id, book_id:b[66].id, tag_id:t8.id)
Tagging.create( user_id:u6.id, book_id:b[40].id, tag_id:t4.id)
Tagging.create( user_id:u6.id, book_id:b[10].id, tag_id:t15.id)
Tagging.create( user_id:u7.id, book_id:b[6].id, tag_id:t9.id)
Tagging.create( user_id:u7.id, book_id:b[25].id, tag_id:t12.id)
Tagging.create( user_id:u7.id, book_id:b[59].id, tag_id:t1.id)
Tagging.create( user_id:u7.id, book_id:b[28].id, tag_id:t14.id)
Tagging.create( user_id:u7.id, book_id:b[62].id, tag_id:t16.id)
Tagging.create( user_id:u7.id, book_id:b[14].id, tag_id:t24.id)
Tagging.create( user_id:u7.id, book_id:b[38].id, tag_id:t2.id)
Tagging.create( user_id:u8.id, book_id:b[19].id, tag_id:t15.id)
Tagging.create( user_id:u8.id, book_id:b[24].id, tag_id:t1.id)
Tagging.create( user_id:u8.id, book_id:b[44].id, tag_id:t12.id)
Tagging.create( user_id:u8.id, book_id:b[33].id, tag_id:t16.id)
Tagging.create( user_id:u8.id, book_id:b[33].id, tag_id:t8.id)
Tagging.create( user_id:u8.id, book_id:b[37].id, tag_id:t12.id)
Tagging.create( user_id:u8.id, book_id:b[30].id, tag_id:t9.id)
Tagging.create( user_id:u9.id, book_id:b[48].id, tag_id:t11.id)
Tagging.create( user_id:u9.id, book_id:b[20].id, tag_id:t25.id)
Tagging.create( user_id:u9.id, book_id:b[21].id, tag_id:t25.id)
Tagging.create( user_id:u9.id, book_id:b[0].id, tag_id:t0.id)
Tagging.create( user_id:u9.id, book_id:b[66].id, tag_id:t1.id)
Tagging.create( user_id:u9.id, book_id:b[24].id, tag_id:t1.id)
Tagging.create( user_id:u9.id, book_id:b[21].id, tag_id:t16.id)
Tagging.create( user_id:u10.id, book_id:b[69].id, tag_id:t15.id)
Tagging.create( user_id:u10.id, book_id:b[4].id, tag_id:t22.id)
Tagging.create( user_id:u10.id, book_id:b[51].id, tag_id:t19.id)
Tagging.create( user_id:u10.id, book_id:b[1].id, tag_id:t23.id)
Tagging.create( user_id:u10.id, book_id:b[26].id, tag_id:t14.id)
Tagging.create( user_id:u10.id, book_id:b[61].id, tag_id:t22.id)
Tagging.create( user_id:u10.id, book_id:b[25].id, tag_id:t28.id)
Tagging.create( user_id:u11.id, book_id:b[67].id, tag_id:t8.id)
Tagging.create( user_id:u11.id, book_id:b[50].id, tag_id:t6.id)
Tagging.create( user_id:u11.id, book_id:b[47].id, tag_id:t16.id)
Tagging.create( user_id:u11.id, book_id:b[35].id, tag_id:t26.id)
Tagging.create( user_id:u11.id, book_id:b[41].id, tag_id:t3.id)
Tagging.create( user_id:u11.id, book_id:b[32].id, tag_id:t26.id)
Tagging.create( user_id:u11.id, book_id:b[39].id, tag_id:t2.id)
Tagging.create( user_id:u12.id, book_id:b[15].id, tag_id:t20.id)
Tagging.create( user_id:u12.id, book_id:b[47].id, tag_id:t16.id)
Tagging.create( user_id:u12.id, book_id:b[11].id, tag_id:t20.id)
Tagging.create( user_id:u12.id, book_id:b[47].id, tag_id:t4.id)
Tagging.create( user_id:u12.id, book_id:b[61].id, tag_id:t9.id)
Tagging.create( user_id:u12.id, book_id:b[13].id, tag_id:t12.id)
Tagging.create( user_id:u12.id, book_id:b[59].id, tag_id:t12.id)
Tagging.create( user_id:u13.id, book_id:b[16].id, tag_id:t26.id)
Tagging.create( user_id:u13.id, book_id:b[35].id, tag_id:t12.id)
Tagging.create( user_id:u13.id, book_id:b[24].id, tag_id:t12.id)
Tagging.create( user_id:u13.id, book_id:b[36].id, tag_id:t20.id)
Tagging.create( user_id:u13.id, book_id:b[63].id, tag_id:t13.id)
Tagging.create( user_id:u13.id, book_id:b[10].id, tag_id:t15.id)
Tagging.create( user_id:u13.id, book_id:b[20].id, tag_id:t16.id)
Tagging.create( user_id:u14.id, book_id:b[65].id, tag_id:t8.id)
Tagging.create( user_id:u14.id, book_id:b[58].id, tag_id:t11.id)
Tagging.create( user_id:u14.id, book_id:b[35].id, tag_id:t3.id)
Tagging.create( user_id:u14.id, book_id:b[56].id, tag_id:t22.id)
Tagging.create( user_id:u14.id, book_id:b[43].id, tag_id:t22.id)
Tagging.create( user_id:u14.id, book_id:b[9].id, tag_id:t16.id)
Tagging.create( user_id:u14.id, book_id:b[17].id, tag_id:t8.id)
Tagging.create( user_id:u15.id, book_id:b[15].id, tag_id:t19.id)
Tagging.create( user_id:u15.id, book_id:b[15].id, tag_id:t21.id)
Tagging.create( user_id:u15.id, book_id:b[52].id, tag_id:t3.id)
Tagging.create( user_id:u15.id, book_id:b[15].id, tag_id:t8.id)
Tagging.create( user_id:u15.id, book_id:b[44].id, tag_id:t18.id)
Tagging.create( user_id:u15.id, book_id:b[42].id, tag_id:t0.id)
Tagging.create( user_id:u15.id, book_id:b[28].id, tag_id:t28.id)
Tagging.create( user_id:u16.id, book_id:b[47].id, tag_id:t1.id)
Tagging.create( user_id:u16.id, book_id:b[32].id, tag_id:t26.id)
Tagging.create( user_id:u16.id, book_id:b[5].id, tag_id:t24.id)
Tagging.create( user_id:u16.id, book_id:b[65].id, tag_id:t4.id)
Tagging.create( user_id:u16.id, book_id:b[59].id, tag_id:t15.id)
Tagging.create( user_id:u16.id, book_id:b[28].id, tag_id:t0.id)
Tagging.create( user_id:u16.id, book_id:b[22].id, tag_id:t8.id)
Tagging.create( user_id:u17.id, book_id:b[34].id, tag_id:t5.id)
Tagging.create( user_id:u17.id, book_id:b[42].id, tag_id:t17.id)
Tagging.create( user_id:u17.id, book_id:b[2].id, tag_id:t9.id)
Tagging.create( user_id:u17.id, book_id:b[44].id, tag_id:t5.id)
Tagging.create( user_id:u17.id, book_id:b[38].id, tag_id:t10.id)
Tagging.create( user_id:u17.id, book_id:b[45].id, tag_id:t9.id)
Tagging.create( user_id:u17.id, book_id:b[0].id, tag_id:t0.id)
Tagging.create( user_id:u18.id, book_id:b[25].id, tag_id:t28.id)
Tagging.create( user_id:u18.id, book_id:b[50].id, tag_id:t26.id)
Tagging.create( user_id:u18.id, book_id:b[40].id, tag_id:t24.id)
Tagging.create( user_id:u18.id, book_id:b[29].id, tag_id:t22.id)
Tagging.create( user_id:u18.id, book_id:b[2].id, tag_id:t24.id)
Tagging.create( user_id:u18.id, book_id:b[65].id, tag_id:t12.id)
Tagging.create( user_id:u18.id, book_id:b[37].id, tag_id:t13.id)
Tagging.create( user_id:u19.id, book_id:b[12].id, tag_id:t13.id)
Tagging.create( user_id:u19.id, book_id:b[9].id, tag_id:t25.id)
Tagging.create( user_id:u19.id, book_id:b[60].id, tag_id:t2.id)
Tagging.create( user_id:u19.id, book_id:b[26].id, tag_id:t21.id)
Tagging.create( user_id:u19.id, book_id:b[2].id, tag_id:t3.id)
Tagging.create( user_id:u19.id, book_id:b[1].id, tag_id:t6.id)
Tagging.create( user_id:u19.id, book_id:b[65].id, tag_id:t12.id)